### ISSUE TITLE
Feature idea: Syntactic indentation for preprocessor statements

### ISSUE THREAD

**Issue by chrivers** [dabrahams/dotemacs#1]
I'm trying to make cc-mode indent preprocessor directives, which turns out is not very easy at all. During some googling, I found your excellent collection of emacs files, and it's the closest I've been to a solution so far - specifically, the "my-electric-pound" helper.

This is what I'm trying to make cc-mode auto-indent:
```
#ifdef DEBUG
    #ifdef FEATURE_A
        #define FOO foo
    #else
        #define FOO bar
    #endif
#endif
```

In my attempt to make this work, I've hacked together this snippet:

```
(defun my-preprocessor-indentation (a)
  (save-excursion
    (beginning-of-line)
    (re-search-backward "^[ \t]*#[ \t]*" nil t)
    (goto-char (match-end 0))
    (+ (current-column)
(if (looking-at "\\(if\\)\\|\\(el\\)") 2 -4))))
```

and then bind it with `(c-set-offset (quote cpp-macro) 'my-preprocessor-indentation)`

And it almost works! In fact, it works for 1 nesting level, for 1 statement (the first). But since this code only looks at the most recent preprocessor line, the preceding `endif` makes it indent to column 0.

I can see that you have looping code for detecting namespace indentation and the like. Do you have some pointers for how to write a similar detection loop that accumulates the preprocessor indentation? I'm not sure how to do this idiomatically.

**Comment by dabrahams** [comment]
I'm afraid I haven't looked at this stuff in so long that I wouldn't be able to say anything useful.

Sorry!

-Dave

**Comment by chrivers** [comment]
That's ok - thanks for the quick reply!
